---
title: "Practica de dplyr"
author: "Irina Pérez Lescano"
format: html
lang: es
toc: true
theme: lux
---

# Introduccion 
Este documento presenta ejemplos de uso de las funciones del paquete dplyr

# Carga de paquetes
```{r}
#| label: carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(knitr)
library(palmerpenguins)
```

# Carga de datos
```{r}
#| label: carga-datoa
#| message: false
#| warning: false

delitos <- read.csv("estadisticaspoliciales2023.csv")
```

# Select

## Ejemplo 1
```{r}
#| label: select-01
#| message: false
#| warning: false

#kable(penguins)

#Seleccion de las columnas de especies, sexo y año
penguins |>
  select(species, sex, year) |>
  kable()
```

## Ejemplo 2
```{r}
#| label: select-02
#| message: false
#| warning: false

# Cambio de nombre de columnas
penguins |>
  select(
    especies = species,
    sexo = sex,
    anio = year
  ) |>
  kable()
```

# filter

## Ejemplo 1
```{r}
#| label: filter-01
#| message: false
#| warning: false

# pinguinos de la especie adelie, machos que son de la isla biscoe

penguins |>
  filter(species == "Adelie", sex == "male", island == "Biscoe") |>
  kable()
```

## Ejemplo 1
```{r}
#| label: filter-02
#| message: false
#| warning: false

# Pinguinos que viven en la isla biscoe o en la isla torgersen

penguins |>
  filter(island == "Biscoe" | island == "Torgersen" |>
           kable()
    
  )
```

## Ejemplo 03
```{r}


# Robos cometidos en el canton de Montes de Oca

delitos |>
  filter(Delito == "ROBO" & Canton == "MONTES DE OCA & Distrito == SAN PEDRO")|>
           select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
           kable()
        
```

## Ejemplo 04
```{r}
#| label: filter-04
#| message: false
#| warning: false

# Pinguinos con Na en la columnas de sexo

penguins |>
  filter(is.na(sex)) |>
  kable()
```

# Arrange

## Ejemplo 01
```{r}
#| label: arrange_01
#| message: false
#| warning: false

delitos |>
  filter(Delito == "ROBO DE VEHICULO" & Canton == "MONTES DE OCA") |>
  select(Delito, SubDelito, Hora, Canton, Distrito) |>
  arrange(Distrito, Hora)|>
  kable()
```

## Ejemplo 02
```{r}
#| label: arrange_02
#| message: false
#| warning: false

penguins |>
  arrange(desc(body_mass_g)) |>
  kable()
```

# Mutate

## Ejemplo 01
```{r}
#| label: mutate_01
#| message: false
#| warning: false

penguins |>
  select(species, body_mass_g) |>
  mutate(body_mass_kg = body_mass_g / 1000) |>
  kable()
```

## Ejemplo 02
```{r}
#| label: mutate_02
#| message: false
#| warning: false

delitos |>
  mutate(Fecha_Date = as.Date(delitos$Fecha, format="%m/%d/%Y")) |>
  filter(Canton == "MONTES DE OCA") |>
  select(Fecha_Date, Canton, Delito, SubDelito) |>
  arrange(Fecha_Date) |>
  kable()
```

# Summarize

## Ejemplo 01
```{r}
#| label: summarize-01
#| message: false
#| warning: false

penguins |>
  group_by(species) |>
  summarize(
    body_mass_g_min = min(body_mass_g, na.rm = TRUE),
    body_mass_g_max = max(body_mass_g, na.rm = TRUE),
    body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
    n = n()
  )
```

## Ejemplo 02
```{r}
#| label: summarize-02
#| message: false
#| warning: false
#| 
# Cantidad de homicidios por provincia y cantón
delitos |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Provincia, Canton) |>
  summarize(
    homicidios_2023 = n()
  ) |>
  arrange(desc(homicidios_2023)) |>
  kable()

```

## Ejemplo 03
```{r}
#| label: summarize-03
#| message: false
#| warning: false
#| 
# Cantidad de homicidios por genero
delitos |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Genero) |>
  summarize(
    homicidios_2023 = n()
  ) |>
  arrange(desc(homicidios_2023)) |>
  kable()

```

## Ejemplo 04
```{r}
#| label: summarize-04
#| message: false
#| warning: false

# Cantidad de asaltos por edad
delitos |>
  filter(Delito == "ASALTO") |>
  group_by(Edad) |>
  summarize(
    homicidios_2023 = n()
  ) |>
  arrange(desc(homicidios_2023)) |>
  kable()

```

## Ejemplo 05
```{r}
#| label: summarize-05
#| message: false
#| warning: false

# Promedio de masa y n cantidad de registros de pingüinos
penguins |>
  summarise(body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
    body_mass_g_min = min(body_mass_g, na.rm = TRUE),
    body_mass_g_max = max(body_mass_g, na.rm = TRUE),
            n = n())
```

